<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
$a = $block->getProductsJson();
?>
<?php  echo $block->getGridHtml(); ?>
<input type="hidden" name="assign[assign_products]" id="assign_products" data-form-part="assign_product_product_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "MageDev_AssignProduct/products/assign-products": {
                "selectedProducts": <?php /* @escapeNotVerified */ echo $block->getProductsJson(); ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */ echo '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
